// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportOutlet.Data;

#nullable disable

namespace SportOutlet.Data.Migrations
{
    [DbContext(typeof(SportOutletDbContext))]
    [Migration("20260429161445_Added Shop Entities")]
    partial class AddedShopEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportOutlet.Data.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Brand Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasComment("Name");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3f9a2e1-7b4d-4c9a-9f2e-6a8d1b3c5e7f"),
                            ImageUrl = "https://i0.wp.com/stickeri.eu/wp-content/uploads/2022/06/nike-500-dark.jpg?fit=500%2C500&ssl=1",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = new Guid("8a1d4f72-2c6b-4e90-b3f7-1d5c9a8e4b21"),
                            ImageUrl = "https://icon2.cleanpng.com/20180528/koj/kisspng-under-armour-hoodie-logo-clothing-armour-5b0c22193ae282.2688990715275218172412.jpg",
                            Name = "Under Armour"
                        },
                        new
                        {
                            Id = new Guid("f7c2b9d4-6e3a-4a1f-8c5d-9e2b7f0a6c13"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg",
                            Name = "Adidas"
                        });
                });

            modelBuilder.Entity("SportOutlet.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasComment("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e2a9c1d-3f7b-4d8e-a6c2-1b9f0e4d7a33"),
                            ImageUrl = "https://www.buzzsneakers.bg/files/thumbs/files/images/slike-proizvoda/media/CW2/CW2288-001/images/thumbs_350/CW2288-001_350_350px.jpg",
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("9c4b7f21-6a8e-4c3d-b2f9-0d1a5e7c8b44"),
                            ImageUrl = "https://static.nike.com/a/images/t_web_pdp_936_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/0cc486f3-e21f-481d-9da5-f897d76a22c1/M+NK+TCH+FLC+JGGR.png",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = new Guid("2f8d1a6b-5c3e-4b9f-a7d2-6e0c4a1b9d55"),
                            ImageUrl = "https://i1.adis.ws/i/jpl/jd_IB4392010_al?w=363&h=363&qlt=90&bg=%23eaeaea",
                            Name = "Equipment"
                        });
                });

            modelBuilder.Entity("SportOutlet.Data.Models.CategoryImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of image");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("From where we get to which category it belongs");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasComment("Example for man or women category");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Url of the image");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3b7a9d1-4c82-4f6a-9b1d-7c2a5e8f9012"),
                            CategoryId = new Guid("5e2a9c1d-3f7b-4d8e-a6c2-1b9f0e4d7a33"),
                            Gender = 0,
                            ImageUrl = "https://www.buzzsneakers.bg/files/thumbs/files/images/slike-proizvoda/media/CW2/CW2288-001/images/thumbs_350/CW2288-001_350_350px.jpg"
                        },
                        new
                        {
                            Id = new Guid("91c5d8a3-2e47-4b6f-8a9c-3f1e7d2b6a34"),
                            CategoryId = new Guid("9c4b7f21-6a8e-4c3d-b2f9-0d1a5e7c8b44"),
                            Gender = 0,
                            ImageUrl = "https://static.nike.com/a/images/t_web_pdp_936_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/0cc486f3-e21f-481d-9da5-f897d76a22c1/M+NK+TCH+FLC+JGGR.png"
                        },
                        new
                        {
                            Id = new Guid("7a2f6c9e-5d81-4a3b-b8c4-9e1f2d7a6b58"),
                            CategoryId = new Guid("2f8d1a6b-5c3e-4b9f-a7d2-6e0c4a1b9d55"),
                            Gender = 0,
                            ImageUrl = "https://i1.adis.ws/i/jpl/jd_IB4392010_al?w=363&h=363&qlt=90&bg=%23eaeaea"
                        },
                        new
                        {
                            Id = new Guid("5d4a9c2e-8f31-4b6a-a7d2-1c9e5f3b7a69"),
                            CategoryId = new Guid("5e2a9c1d-3f7b-4d8e-a6c2-1b9f0e4d7a33"),
                            Gender = 1,
                            ImageUrl = "https://i8.amplience.net/s/scvl/178735_396397_SET/1?fmt=auto"
                        },
                        new
                        {
                            Id = new Guid("c1b7e4a9-3d82-4f6c-9a5e-2b7d1f8c6a70"),
                            CategoryId = new Guid("9c4b7f21-6a8e-4c3d-b2f9-0d1a5e7c8b44"),
                            Gender = 1,
                            ImageUrl = "https://nikestrength.com/cdn/shop/files/BLK-PHOENIX-CREWNECK-WOMENS-FRONT_533x.jpg?v=1762461327"
                        },
                        new
                        {
                            Id = new Guid("8f2c6a1d-7b93-4a5e-b9c1-3d7a2e6f5b81"),
                            CategoryId = new Guid("2f8d1a6b-5c3e-4b9f-a7d2-6e0c4a1b9d55"),
                            Gender = 1,
                            ImageUrl = "https://images.asos-media.com/products/nike-everyday-plus-cushioned-frilly-sock-in-lilac/201059358-1-lilac?$n_750w$&wid=750&hei=750&fit=crop"
                        },
                        new
                        {
                            Id = new Guid("2c8f5a1e-9d47-4b6a-8e2c-7a1d3f9b6c92"),
                            CategoryId = new Guid("5e2a9c1d-3f7b-4d8e-a6c2-1b9f0e4d7a33"),
                            Gender = 3,
                            ImageUrl = "https://todaysparent.mblycdn.com/tp/resized/2024/06/1600x1200/The-Best-Nike-Shoes-for-Kids-2024.png"
                        },
                        new
                        {
                            Id = new Guid("b6a1d9e3-4c82-4f7b-a5d1-8c3e2a7f9d03"),
                            CategoryId = new Guid("9c4b7f21-6a8e-4c3d-b2f9-0d1a5e7c8b44"),
                            Gender = 3,
                            ImageUrl = "https://images.prodirectsport.com/ProductImages/Main/420123_Main_Thumb_1699808.jpg"
                        },
                        new
                        {
                            Id = new Guid("9e3b7c2a-5d81-4a6f-b8c4-1f2d7a9c6b14"),
                            CategoryId = new Guid("2f8d1a6b-5c3e-4b9f-a7d2-6e0c4a1b9d55"),
                            Gender = 3,
                            ImageUrl = "https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/4018511d-ba37-4f07-9dfe-7bbb2e8ee61a/UPF+40%2B+INFANT+BUCKET+HAT.png"
                        });
                });

            modelBuilder.Entity("SportOutlet.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("BrandBelonging");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Description");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasComment("Sizing");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Hiding when out of stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("SubCategoryBelonging");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f1c7a2e-8b93-4d6f-a5e1-2c9d7b3a6f10"),
                            BrandId = new Guid("c3f9a2e1-7b4d-4c9a-9f2e-6a8d1b3c5e7f"),
                            Description = "The Nike Air Max Pulse Men's Shoe combines London-inspired style with enhanced point-loaded Air cushioning for a fresh look and better performance.\r\n\r\n\r\nDetails\r\nPoint-load cushioning system features a plastic clip that distributes weight to targeted points in the Air module, providing a unique, springy feel\r\nPerformance comfort, reimagined for the street\r\nFoam midsole\r\nRubber outsole",
                            Gender = 0,
                            IsActive = true,
                            Name = "Nike Air Max Pulse",
                            Price = 125.25m,
                            SubCategoryId = new Guid("1a7f3c5e-9d24-4b8a-a1f6-3e9c2d7b6a11")
                        },
                        new
                        {
                            Id = new Guid("a2d9e6c4-5b71-4f8a-9c3d-7e1b2f6a8c21"),
                            BrandId = new Guid("8a1d4f72-2c6b-4e90-b3f7-1d5c9a8e4b21"),
                            Description = "Longer distances and faster runs start with maximum comfort. The Under Armour Launch Men's Running T-Shirt is soft, stretchy and so lightweight it feels like you're wearing nothing.\r\n\r\n\r\nDetail:\r\nSoft, lightweight and breathable fabric designed for complete comfort on every run\r\nMoisture-wicking and quick-drying fabric\r\nOverlapping detail improves ventilation for better airflow\r\nReflective details improve visibility in low light\r\nOdor control technology helps you stay fresh\r\nMaterial: 94% polyester, 6% polyester",
                            Gender = 0,
                            IsActive = true,
                            Name = "Under Armour Launch",
                            Price = 27.99m,
                            SubCategoryId = new Guid("7d2c4e1a-8b9f-4a63-a2e5-1c7b3d9f0a44")
                        },
                        new
                        {
                            Id = new Guid("7b3e1f9a-2c6d-4a85-b8f0-5d2c9e7a1b32"),
                            BrandId = new Guid("f7c2b9d4-6e3a-4a1f-8c5d-9e2b7f0a6c13"),
                            Description = "With this adidas Linear training bag you will stay organized while you are on the go.\r\n\r\n\r\nDetails\r\nDimensions: 22 cm x 56 cm x 28 cm\r\nVolume: 39.75 l\r\nSide and end pockets with zipper\r\nInternal zip pockets\r\nSeparate shoe compartment\r\nAdjustable shoulder strap with removable padding\r\nTwo padded carrying handles\r\n\r\nEco Story\r\nThis product is made from 50% recycled materials",
                            Gender = 2,
                            IsActive = true,
                            Name = "adidas Linear",
                            Price = 24.69m,
                            SubCategoryId = new Guid("d9f4b2a1-6c7e-4a83-b5d9-2f1c8e7a3b99")
                        },
                        new
                        {
                            Id = new Guid("c8a2d5f1-9e47-4b6c-a3f8-1d7b2c9e6a43"),
                            BrandId = new Guid("c3f9a2e1-7b4d-4c9a-9f2e-6a8d1b3c5e7f"),
                            Description = "The Nike Offline Chill Women's Pants are designed for everyday comfort and a casual style.\r\n\r\n\r\nDetails\r\nLightweight French terry fabric combines the feel of fleece and jersey knitwear\r\nLoose fit makes movement easier\r\nEmbroidered Swoosh logo adds a subtle, recognizable accent\r\nPadded elastic waistband with internal drawcord ensures a secure fit\r\nPin tuck details add an elegant tailoring accent\r\nSide seam pockets hold small essentials\r\nOpen hem creates a relaxed silhouette\r\nFabric: 70% cotton, 30% polyester",
                            Gender = 1,
                            IsActive = true,
                            Name = "Nike Offline Chill",
                            Price = 64.99m,
                            SubCategoryId = new Guid("c2f7e1a9-4b6d-4d83-a8c5-3e1b9f7a2c77")
                        },
                        new
                        {
                            Id = new Guid("1e9b3c7d-4a2f-4d86-b5c1-8a7e2d6f9c54"),
                            BrandId = new Guid("8a1d4f72-2c6b-4e90-b3f7-1d5c9a8e4b21"),
                            Description = "When cold, wet weather won't stop your workout, this Under Armour Unstoppable Men's Jacket is the choice for you. Ultra-light and stretchy, it repels rain, keeps you warm (but not too hot), and moves with you through every workout.\r\n\r\n\r\nDetails:\r\nStretchy woven fabric is strong yet lightweight for durability and comfort\r\n4-way stretch material moves better in every direction for unrestricted movement\r\nWater-repellent coating helps you stay dry in wet conditions\r\nSecure zippered hand pockets keep your essentials safe. Bungee cord hem adjusts for a secure, personalized fit.",
                            Gender = 1,
                            IsActive = true,
                            Name = "Under Armour Unstoppable",
                            Price = 53.68m,
                            SubCategoryId = new Guid("6b1d9a4f-3e7c-4a82-b5d1-8f2e6c9a0b66")
                        },
                        new
                        {
                            Id = new Guid("f4a8c2d1-9b37-4e6f-a5c2-8d1e7b3f9a62"),
                            BrandId = new Guid("8a1d4f72-2c6b-4e90-b3f7-1d5c9a8e4b21"),
                            Description = "Stay light, supported and ready to move with the Under Armour Launch 7'' 2-in-1 Men's Running Shorts, designed to provide comfort, breathability and high performance on every run.\r\n\r\n\r\nDetails\r\nLightweight woven outer shorts provide comfort and durability\r\nBuilt-in knit compression shorts give extra coverage and support\r\nSweat-wicking fabric dries quickly to keep you dry and comfortable\r\nHighly breathable mesh panels enhance ventilation\r\nSoft knit waistband with internal drawcord provides a secure and comfortable fit\r\nOpen hand pockets include an internal phone pocket on the right\r\n\r\nEco story\r\nThe main fabric contains at least 90% recycled polyester, excluding finishing and decorative elements, to reduce waste and carbon emissions.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Under Armour Launch 7'' 2-in-1",
                            Price = 49.99m,
                            SubCategoryId = new Guid("a9e3b7d2-1c5f-4b8a-9d6e-2f7c1a3b8e55")
                        },
                        new
                        {
                            Id = new Guid("0c9e7a1d-3b5f-4a82-b6c1-2d7f8e3a9b73"),
                            BrandId = new Guid("c3f9a2e1-7b4d-4c9a-9f2e-6a8d1b3c5e7f"),
                            Description = "These Jordan Sport Essentials Men's Woven Shorts with Dri-FIT are called Essentials for a reason. They're made with a four-way stretch woven fabric and sweat-wicking technology to help keep you comfortable on and off the court.\r\n\r\n\r\nDetails\r\nNike Dri-FIT technology wicks sweat away from the skin for faster evaporation, helping you stay dry and comfortable\r\nSide pockets for storing your small items\r\nMain: 88% polyester/12% elastane. Mesh: 100% polyester\r\nMachine wash\r\n\r\nEco story This product is made with recycled materials",
                            Gender = 0,
                            IsActive = true,
                            Name = "Nike Sportswear Jordan",
                            Price = 39.99m,
                            SubCategoryId = new Guid("a9e3b7d2-1c5f-4b8a-9d6e-2f7c1a3b8e55")
                        });
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasComment("Should have order to prevent chaos");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Belongs to a product");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c2f9e1a-3b7d-4a85-9f2c-8d1e7b3a5c60"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/HJ5/HJ5178-001/images/thumbs_600/HJ5178-001_600_600px.jpg",
                            Order = 1,
                            ProductId = new Guid("4f1c7a2e-8b93-4d6f-a5e1-2c9d7b3a6f10")
                        },
                        new
                        {
                            Id = new Guid("b7a1d3c9-5e2f-4d88-a6c4-2f9e1b7a3d71"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/HJ5/HJ5178-001/images/thumbs_600/HJ5178-001_1_600_600px.jpg",
                            Order = 2,
                            ProductId = new Guid("4f1c7a2e-8b93-4d6f-a5e1-2c9d7b3a6f10")
                        },
                        new
                        {
                            Id = new Guid("2d8c5a7e-1f3b-4a9c-b6d2-9e7a1c3f8b82"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/HJ5/HJ5178-001/images/thumbs_600/HJ5178-001_2_600_600px.jpg",
                            Order = 3,
                            ProductId = new Guid("4f1c7a2e-8b93-4d6f-a5e1-2c9d7b3a6f10")
                        },
                        new
                        {
                            Id = new Guid("e1a7b4c2-6d9f-4a83-8c5e-3b2d7a9f1c93"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/HJ5/HJ5178-001/images/thumbs_600/HJ5178-001_3_600_600px.jpg",
                            Order = 4,
                            ProductId = new Guid("4f1c7a2e-8b93-4d6f-a5e1-2c9d7b3a6f10")
                        },
                        new
                        {
                            Id = new Guid("9b2e6d4f-1a73-4c8e-b5d2-7f3a1c9e6d04"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/138/1382582-001/images/thumbs_600/1382582-001_600_600px.jpg",
                            Order = 5,
                            ProductId = new Guid("a2d9e6c4-5b71-4f8a-9c3d-7e1b2f6a8c21")
                        },
                        new
                        {
                            Id = new Guid("3c7a1f9e-5b2d-4a86-8e1c-2d9f7b3a6c15"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/138/1382582-001/images/thumbs_600/1382582-001_1_600_600px.jpg",
                            Order = 6,
                            ProductId = new Guid("a2d9e6c4-5b71-4f8a-9c3d-7e1b2f6a8c21")
                        },
                        new
                        {
                            Id = new Guid("d2a7c5e1-4b9f-4a86-8c3d-6e1f2b7a9c26"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/JD9/JD9555/images/thumbs_600/JD9555_600_600px.jpg",
                            Order = 7,
                            ProductId = new Guid("7b3e1f9a-2c6d-4a85-b8f0-5d2c9e7a1b32")
                        },
                        new
                        {
                            Id = new Guid("5f3e1a7c-9d2b-4c88-a6f1-3b7e2d9c1a37"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/JD9/JD9555/images/thumbs_600/JD9555_2_600_600px.jpg",
                            Order = 8,
                            ProductId = new Guid("7b3e1f9a-2c6d-4a85-b8f0-5d2c9e7a1b32")
                        },
                        new
                        {
                            Id = new Guid("a9c2b7d4-6e1f-4a83-9f5c-2d3b7a1e8c48"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/JD9/JD9555/images/thumbs_600/JD9555_3_600_600px.jpg",
                            Order = 9,
                            ProductId = new Guid("7b3e1f9a-2c6d-4a85-b8f0-5d2c9e7a1b32")
                        },
                        new
                        {
                            Id = new Guid("f1a9d3c7-6e2b-4a85-8c1f-3d7b9e2a5c61"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/II3/II3978-323/images/thumbs_600/II3978-323_600_600px.jpg",
                            Order = 10,
                            ProductId = new Guid("c8a2d5f1-9e47-4b6c-a3f8-1d7b2c9e6a43")
                        },
                        new
                        {
                            Id = new Guid("8e4b2a1d-7c9f-4a86-b3d5-1a2e7c9f6b72"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/II3/II3978-323/images/thumbs_600/II3978-323_1_600_600px.jpg",
                            Order = 11,
                            ProductId = new Guid("c8a2d5f1-9e47-4b6c-a3f8-1d7b2c9e6a43")
                        },
                        new
                        {
                            Id = new Guid("2a7c9e5d-3b1f-4a83-9d6e-5c2b7a1f8e83"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/II3/II3978-323/images/thumbs_600/II3978-323_3_600_600px.jpg",
                            Order = 12,
                            ProductId = new Guid("c8a2d5f1-9e47-4b6c-a3f8-1d7b2c9e6a43")
                        },
                        new
                        {
                            Id = new Guid("c4a7e2b1-9d3f-4a86-8c5e-2f1b7a9d6c94"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/137/1374889-696/images/thumbs_600/1374889-696_600_600px.jpg",
                            Order = 13,
                            ProductId = new Guid("1e9b3c7d-4a2f-4d86-b5c1-8a7e2d6f9c54")
                        },
                        new
                        {
                            Id = new Guid("7d1b3c9e-5a2f-4a83-b6e1-9c7a2d5f8e05"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/137/1374889-696/images/thumbs_600/1374889-696_1_600_600px.jpg",
                            Order = 14,
                            ProductId = new Guid("1e9b3c7d-4a2f-4d86-b5c1-8a7e2d6f9c54")
                        },
                        new
                        {
                            Id = new Guid("1f9c2a7d-3e5b-4a88-8d1f-6b2c7e9a3d16"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/137/1374889-696/images/thumbs_600/1374889-696_2_600_600px.jpg",
                            Order = 15,
                            ProductId = new Guid("1e9b3c7d-4a2f-4d86-b5c1-8a7e2d6f9c54")
                        },
                        new
                        {
                            Id = new Guid("e7a3d1c5-8b2f-4a84-9c6e-3f1a7d2b5c27"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/137/1374889-696/images/thumbs_600/1374889-696_3_600_600px.jpg",
                            Order = 16,
                            ProductId = new Guid("1e9b3c7d-4a2f-4d86-b5c1-8a7e2d6f9c54")
                        },
                        new
                        {
                            Id = new Guid("3a9f7c2e-6d14-4b8a-9c5e-1f2d7a8b6c91"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/138/1382641-001/images/thumbs_600/1382641-001_600_600px.jpg",
                            Order = 17,
                            ProductId = new Guid("f4a8c2d1-9b37-4e6f-a5c2-8d1e7b3f9a62")
                        },
                        new
                        {
                            Id = new Guid("b5e1a9d3-2c74-4f6b-8a3d-9e7c1f2a6b04"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/138/1382641-001/images/thumbs_600/1382641-001_1_600_600px.jpg",
                            Order = 18,
                            ProductId = new Guid("f4a8c2d1-9b37-4e6f-a5c2-8d1e7b3f9a62")
                        },
                        new
                        {
                            Id = new Guid("7c2d8a1e-5f93-4a6b-b9c1-3e7f2a4d8c56"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/138/1382641-001/images/thumbs_600/1382641-001_2_600_600px.jpg",
                            Order = 19,
                            ProductId = new Guid("f4a8c2d1-9b37-4e6f-a5c2-8d1e7b3f9a62")
                        },
                        new
                        {
                            Id = new Guid("c9e4a7d2-1b83-4f6a-9c5d-2e7a1f8b3d64"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/IF2/IF2160-010/images/thumbs_600/IF2160-010_600_600px.jpg",
                            Order = 20,
                            ProductId = new Guid("0c9e7a1d-3b5f-4a82-b6c1-2d7f8e3a9b73")
                        },
                        new
                        {
                            Id = new Guid("4b7f2c9e-6a15-4d8b-b3c1-9e2a7f5d8c73"),
                            ImageUrl = "https://www.sportvision.bg/files/thumbs/files/images/slike_proizvoda/media/IF2/IF2160-010/images/thumbs_600/IF2160-010_1_600_600px.jpg",
                            Order = 21,
                            ProductId = new Guid("0c9e7a1d-3b5f-4a82-b6c1-2d7f8e3a9b73")
                        });
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ProductSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasComment("Material type");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Is for product");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSpecifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1c5e9d2-7b3f-4a86-8d1c-9e2f7b3a6c38"),
                            Key = "Color",
                            ProductId = new Guid("4f1c7a2e-8b93-4d6f-a5e1-2c9d7b3a6f10"),
                            Value = "Black"
                        },
                        new
                        {
                            Id = new Guid("6e2b7a1d-9c3f-4a83-b5d1-2f8a7c9e4d49"),
                            Key = "Color",
                            ProductId = new Guid("a2d9e6c4-5b71-4f8a-9c3d-7e1b2f6a8c21"),
                            Value = "Black"
                        },
                        new
                        {
                            Id = new Guid("d3a7c1e9-5b2f-4a88-9c6e-7d1a2b3f8c50"),
                            Key = "Color",
                            ProductId = new Guid("7b3e1f9a-2c6d-4a85-b8f0-5d2c9e7a1b32"),
                            Value = "Black"
                        },
                        new
                        {
                            Id = new Guid("2b9e5a7c-1d3f-4a84-8c2e-6f7a1b9d3c61"),
                            Key = "Color",
                            ProductId = new Guid("c8a2d5f1-9e47-4b6c-a3f8-1d7b2c9e6a43"),
                            Value = "Green"
                        },
                        new
                        {
                            Id = new Guid("f8c1a3d7-6e2b-4a85-9d5f-3b7a2c1e8d72"),
                            Key = "Color",
                            ProductId = new Guid("1e9b3c7d-4a2f-4d86-b5c1-8a7e2d6f9c54"),
                            Value = "Pink"
                        },
                        new
                        {
                            Id = new Guid("6f1a9c3e-2b74-4d8a-9c5e-1e7a3f8b6c92"),
                            Key = "Color",
                            ProductId = new Guid("f4a8c2d1-9b37-4e6f-a5c2-8d1e7b3f9a62"),
                            Value = "Black"
                        },
                        new
                        {
                            Id = new Guid("d3b7e2a1-9c54-4f6a-8d1c-2a7f9e3b6c81"),
                            Key = "Color",
                            ProductId = new Guid("0c9e7a1d-3b5f-4a82-b6c1-2d7f8e3a9b73"),
                            Value = "Black"
                        });
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("For a product");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Size");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasComment("Stock");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2a9c1e-7d5b-4a86-8c1f-9b2e7a3d6c83"),
                            ProductId = new Guid("4f1c7a2e-8b93-4d6f-a5e1-2c9d7b3a6f10"),
                            Size = "44.5",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("b1e7d3a9-5c2f-4a84-9d6e-2a3f7c1b8d94"),
                            ProductId = new Guid("4f1c7a2e-8b93-4d6f-a5e1-2c9d7b3a6f10"),
                            Size = "45",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("8c5a1d7e-2f3b-4a83-b9d1-7e6a2c3f1b05"),
                            ProductId = new Guid("a2d9e6c4-5b71-4f8a-9c3d-7e1b2f6a8c21"),
                            Size = "L",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("d7a3c1f9-6b2e-4a88-8c5d-1f9e2b3a7c16"),
                            ProductId = new Guid("a2d9e6c4-5b71-4f8a-9c3d-7e1b2f6a8c21"),
                            Size = "XL",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("1c9e7a2d-3b5f-4a85-9d1e-6a7c2b3f8e27"),
                            ProductId = new Guid("7b3e1f9a-2c6d-4a85-b8f0-5d2c9e7a1b32"),
                            Size = "Adjustable",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("6a2d3f9c-1e7b-4a86-8c5f-3d1b7a9e2c38"),
                            ProductId = new Guid("c8a2d5f1-9e47-4b6c-a3f8-1d7b2c9e6a43"),
                            Size = "S",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("f3b1a7c9-2d5e-4a84-b6c1-8e7a3d2f9c49"),
                            ProductId = new Guid("c8a2d5f1-9e47-4b6c-a3f8-1d7b2c9e6a43"),
                            Size = "M",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("2e7c1a5d-9b3f-4a83-8d6e-1c2f7a9b3d50"),
                            ProductId = new Guid("1e9b3c7d-4a2f-4d86-b5c1-8a7e2d6f9c54"),
                            Size = "S",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("9d1a3c7f-5b2e-4a88-9c6d-2f7a1e3b8c61"),
                            ProductId = new Guid("1e9b3c7d-4a2f-4d86-b5c1-8a7e2d6f9c54"),
                            Size = "M",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("1d7a9c3e-5b24-4f6a-8c1d-2e9f7b3a6c85"),
                            ProductId = new Guid("f4a8c2d1-9b37-4e6f-a5c2-8d1e7b3f9a62"),
                            Size = "L",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("8b2f6d1c-9a73-4e5a-b4c2-7d1e3f9a6c08"),
                            ProductId = new Guid("f4a8c2d1-9b37-4e6f-a5c2-8d1e7b3f9a62"),
                            Size = "XL",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("5e3c1a7d-2f94-4b6a-9d1c-8a2e7f3b6c19"),
                            ProductId = new Guid("0c9e7a1d-3b5f-4a82-b6c1-2d7f8e3a9b73"),
                            Size = "L",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("a2f9b6c3-4d71-4e8a-8c5d-3e7a1f2b9c60"),
                            ProductId = new Guid("0c9e7a1d-3b5f-4a82-b6c1-2d7f8e3a9b73"),
                            Size = "XL",
                            Stock = 20
                        });
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ShopEntities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of cart");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who ordered");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ShopEntities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of CartItem");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of Cart");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of product");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("How many items");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ShopEntities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of Order");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Keep record of the date and time purchased");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the order");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User for whom the order is created");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ShopEntities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of the ordered item");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Belongs to an order");

                    b.Property<Guid?>("OrderId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Given product");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of ordered items");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("currentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderId1");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Successor of category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasComment("Name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a7f3c5e-9d24-4b8a-a1f6-3e9c2d7b6a11"),
                            CategoryId = new Guid("5e2a9c1d-3f7b-4d8e-a6c2-1b9f0e4d7a33"),
                            Name = "Sneakers"
                        },
                        new
                        {
                            Id = new Guid("b4c2d8f1-6a93-4e7b-9f0a-5c1d2e8f7a22"),
                            CategoryId = new Guid("5e2a9c1d-3f7b-4d8e-a6c2-1b9f0e4d7a33"),
                            Name = "Running Shoes"
                        },
                        new
                        {
                            Id = new Guid("3e9a1b6c-5d72-4f8a-b3c1-7a2d9e4f6b33"),
                            CategoryId = new Guid("5e2a9c1d-3f7b-4d8e-a6c2-1b9f0e4d7a33"),
                            Name = "Lifestyle sneakers"
                        },
                        new
                        {
                            Id = new Guid("7d2c4e1a-8b9f-4a63-a2e5-1c7b3d9f0a44"),
                            CategoryId = new Guid("9c4b7f21-6a8e-4c3d-b2f9-0d1a5e7c8b44"),
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = new Guid("a9e3b7d2-1c5f-4b8a-9d6e-2f7c1a3b8e55"),
                            CategoryId = new Guid("9c4b7f21-6a8e-4c3d-b2f9-0d1a5e7c8b44"),
                            Name = "Shorts"
                        },
                        new
                        {
                            Id = new Guid("6b1d9a4f-3e7c-4a82-b5d1-8f2e6c9a0b66"),
                            CategoryId = new Guid("9c4b7f21-6a8e-4c3d-b2f9-0d1a5e7c8b44"),
                            Name = "Sweatshirts"
                        },
                        new
                        {
                            Id = new Guid("c2f7e1a9-4b6d-4d83-a8c5-3e1b9f7a2c77"),
                            CategoryId = new Guid("9c4b7f21-6a8e-4c3d-b2f9-0d1a5e7c8b44"),
                            Name = "Pants"
                        },
                        new
                        {
                            Id = new Guid("8e5a2c7d-9f1b-4a6e-b3d8-6c2f0a1e9b88"),
                            CategoryId = new Guid("2f8d1a6b-5c3e-4b9f-a7d2-6e0c4a1b9d55"),
                            Name = "Socks"
                        },
                        new
                        {
                            Id = new Guid("d9f4b2a1-6c7e-4a83-b5d9-2f1c8e7a3b99"),
                            CategoryId = new Guid("2f8d1a6b-5c3e-4b9f-a7d2-6e0c4a1b9d55"),
                            Name = "Bags and Sacks"
                        });
                });

            modelBuilder.Entity("SportOutlet.Data.Models.CategoryImage", b =>
                {
                    b.HasOne("SportOutlet.Data.Models.Category", "Category")
                        .WithMany("CategoryImages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.Product", b =>
                {
                    b.HasOne("SportOutlet.Data.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportOutlet.Data.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ProductImage", b =>
                {
                    b.HasOne("SportOutlet.Data.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ProductSpecification", b =>
                {
                    b.HasOne("SportOutlet.Data.Models.Product", "Product")
                        .WithMany("ProductSpecifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ProductVariant", b =>
                {
                    b.HasOne("SportOutlet.Data.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ShopEntities.CartItem", b =>
                {
                    b.HasOne("SportOutlet.Data.Models.ShopEntities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportOutlet.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ShopEntities.OrderItem", b =>
                {
                    b.HasOne("SportOutlet.Data.Models.ShopEntities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportOutlet.Data.Models.ShopEntities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId1");

                    b.HasOne("SportOutlet.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.SubCategory", b =>
                {
                    b.HasOne("SportOutlet.Data.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.Category", b =>
                {
                    b.Navigation("CategoryImages");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductSpecifications");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ShopEntities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.ShopEntities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SportOutlet.Data.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
